# 📊 Trực Quan Hiện Trạng Lớp Silver (MinIO)

Chạy Notebook này để xem dữ liệu của từng bảng dưới dạng Dataframe trực quan (HTML Pandas).

In [1]:
import sys, os

# === Cấu hình kết nối MinIO Server ===
os.environ['MINIO_ENDPOINT'] = 'http://20.41.113.183:9000'
os.environ['MINIO_ACCESS_KEY'] = 'minioadmin'
os.environ['MINIO_SECRET_KEY'] = 'minioadmin123'

if 'SEED_PATH' in os.environ:
    del os.environ['SEED_PATH']

if 'google.colab' in sys.modules:
    !rm -rf /content/Lab
    !git clone -b ml https://github.com/nbngoc123/Lab.git /content/Lab
    os.chdir('/content/Lab/football-lake')
    sys.path.insert(0, '/content/Lab/football-lake')
    !pip install minio duckdb pandas understatapi boto3 python-dotenv -q
    print('Setup xong cho Colab!')
else:
    # Chạy trên máy ảo (VM) hoặc local
    PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..'))
    if PROJECT_ROOT not in sys.path:
        sys.path.insert(0, PROJECT_ROOT)
    print(f'Thêm {PROJECT_ROOT} vào sys.path để nhận diện thư viện lake')

Cloning into '/content/Lab'...
remote: Enumerating objects: 1021, done.
remote: Counting objects: 100% (155/155), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 1021 (delta 66), reused 110 (delta 35), pack-reused 866 (from 1)
Receiving objects: 100% (1021/1021), 75.43 MiB | 25.11 MiB/s, done.
Resolving deltas: 100% (488/488), done.
Setup xong cho Colab!

In [2]:
import os
import io
import pandas as pd
from IPython.display import display, HTML
from lake import minio_io as mio

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 1000)

print('Đã load thư viện thành công. Sẵn sàng kết nối MinIO...')

Đã load thư viện thành công. Sẵn sàng kết nối MinIO...

In [3]:
files = list(mio.list_keys("silver/"))

datasets = {}
for key, size in files:
    if not key.endswith(".parquet"): continue
    parts = key.split("/")
    if len(parts) >= 3:
        ds_name = f"{parts[1]}/{parts[2]}"
        datasets.setdefault(ds_name, []).append((key, size))

for ds_name, file_list in sorted(datasets.items()):
    display(HTML(f"<h3>⚽ Bảng: <span style='color: #2c3e50;'>{ds_name}</span></h3>"))
    
    sample_key = file_list[0][0]
    try:
        raw = mio.read_bytes(sample_key)
        df = pd.read_parquet(io.BytesIO(raw))
        
        info_html = f"""
        <ul>
            <li><b>Số lượng file (partition):</b> {len(file_list)}</li>
            <li><b>Số cột:</b> {len(df.columns)}</li>
            <li><b>Số ô Null (mẫu):</b> {df.isna().sum().sum()}</li>
        </ul>
        """
        display(HTML(info_html))
        display(df.head(5))
        display(HTML("<hr>"))
        
    except Exception as e:
        display(HTML(f"<p style='color: red;'>Lỗi khi đọc: {e}</p>"))

                           match_id home_team     away_team             commence_time     bookmaker               last_update  odds_home  odds_draw  odds_away ingest_date
0  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00   Unibet (UK) 2026-09-22 07:58:56+00:00       1.37       4.75        7.5  2026-09-22
1  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00   Codere (IT) 2026-09-22 07:58:55+00:00       1.38       5.00        7.8  2026-09-22
2  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  Betfred (UK) 2026-09-22 07:58:55+00:00       1.33       5.00        9.0  2026-09-22
3  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00   Unibet (FR) 2026-09-22 07:58:54+00:00       1.31       4.50        7.0  2026-09-22
4  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  Winamax (DE) 2026-09-22 07:58:55+00:00       1.35       5.00        7.0  2026-09-22

                           match_id home_team     away_team             commence_time    bookmaker               last_update          team  point  price ingest_date
0  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00        1xBet 2026-09-22 07:59:16+00:00       Arsenal  -1.50   2.15  2026-09-22
1  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00        1xBet 2026-09-22 07:59:16+00:00  Leeds United   1.50   1.81  2026-09-22
2  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  MyBookie.ag 2026-09-22 07:58:18+00:00       Arsenal  -1.50   2.02  2026-09-22
3  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  MyBookie.ag 2026-09-22 07:58:18+00:00  Leeds United   1.50   1.71  2026-09-22
4  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00     Pinnacle 2026-09-22 07:59:54+00:00       Arsenal  -1.25   1.85  2026-09-22

                           match_id home_team     away_team             commence_time    bookmaker               last_update   name  point  price ingest_date
0  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  Codere (IT) 2026-09-22 07:58:55+00:00   Over    2.5   1.67  2026-09-22
1  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  Codere (IT) 2026-09-22 07:58:55+00:00  Under    2.5   2.03  2026-09-22
2  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00        1xBet 2026-09-22 07:59:16+00:00   Over    2.5   1.83  2026-09-22
3  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00        1xBet 2026-09-22 07:59:16+00:00  Under    2.5   2.14  2026-09-22
4  b870dcfba5e5920d3f1551a3aa1ea435   Arsenal  Leeds United 2026-10-10 11:30:00+00:00  MyBookie.ag 2026-09-22 07:58:18+00:00   Over    2.5   1.69  2026-09-22

   competition_id  code                                   name       area    type  current_season_id current_season_start  current_matchday
0            2193   ACQ  Africa Cup Of Nations - Qualification     Africa     CUP             2545.0           2026-09-23               1.0
1            2006  QCAF                   WC Qualification CAF     Africa     CUP             1609.0           2023-11-15              10.0
2            2176    AC                  Africa Cup Of Nations     Africa     CUP             2385.0           2025-12-21               3.0
3            2166   ACL                   AFC Champions League     Africa     CUP             1559.0           2022-04-06               NaN
4            2023   PBN                     Primera B Nacional  Argentina  LEAGUE             2500.0           2026-06-17              30.0

   player_id               name    position date_of_birth nationality  team_id   team_name
0       7015   Matthias Köbbing  Goalkeeper    1997-05-28     Germany        1  1. FC Köln
1       9388  Ron-Robert Zieler  Goalkeeper    1989-02-12     Germany        1  1. FC Köln
2       9957     Marvin Schwäbe  Goalkeeper    1995-04-25     Germany        1  1. FC Köln
3     289578       Martin James  Goalkeeper    2008-02-14      France        1  1. FC Köln
4        309        Timo Hübers     Defence    1996-07-20     Germany        1  1. FC Köln

   team_id                 name  short_name  tla  founded                venue          club_colors       coach_name coach_nationality  squad_size competition
0        1           1. FC Köln  1. FC Köln  KOE     1948  RheinEnergieSTADION          Red / White      René Wagner           Germany          31         BL1
1        2  TSG 1899 Hoffenheim  Hoffenheim  TSG     1921        PreZero Arena         Blue / White  Christian Ilzer           Austria          28         BL1
2        3  Bayer 04 Leverkusen  Leverkusen  B04     1904             BayArena  Red / White / Black  Carles Martínez             Spain          29         BL1
3        4    Borussia Dortmund    Dortmund  BVB     1909    Signal Iduna Park       Black / Yellow       Niko Kovać           Croatia          30         BL1
4        5    FC Bayern München      Bayern  FCB     1900        Allianz Arena   Red / White / Blue  Vincent Kompany           Belgium          24         BL1

     venue            datetime  temperature_c  precipitation_mm  windspeed_kmh  humidity_pct  weathercode
0  Anfield 2025-08-01 00:00:00           15.1               0.0           16.8            81            2
1  Anfield 2025-08-01 01:00:00           14.9               0.0           16.5            82            2
2  Anfield 2025-08-01 02:00:00           14.5               0.0           16.2            79            2
3  Anfield 2025-08-01 03:00:00           14.4               0.0           14.4            79            2
4  Anfield 2025-08-01 04:00:00           14.3               0.0           15.0            81            2

               team  rank  total_injuries ingest_date
0         Brentford     1               7  2026-09-21
1           Burnley     2               7  2026-09-21
2        Sunderland     3               7  2026-09-21
3           Chelsea     4               6  2026-09-21
4  Newcastle United     5               6  2026-09-21

   count     injury_type ingest_date
0     21            Knee  2026-09-21
1     12      Ankle/Foot  2026-09-21
2     12           Thigh  2026-09-21
3      8           Other  2026-09-21
4      4  Calf/Shin/Heel  2026-09-21

                                              s3_key entity entity_id image_role content_type  size_bytes  sha256                                         source_url ingest_date
0  bronze/thesportsdb/media/entity=team/team_id=1...   team    133604      badge    image/png      127571  cached  https://r2.thesportsdb.com/images/media/team/b...  2026-09-21
1  bronze/thesportsdb/media/entity=team/team_id=1...   team    133604       logo    image/png       24167  cached  https://r2.thesportsdb.com/images/media/team/l...  2026-09-21
2  bronze/thesportsdb/media/entity=team/team_id=1...   team    133604     banner   image/jpeg       68993  cached  https://r2.thesportsdb.com/images/media/team/b...  2026-09-21
3  bronze/thesportsdb/media/entity=team/team_id=1...   team    133604  equipment    image/png      281142  cached  https://r2.thesportsdb.com/images/media/team/e...  2026-09-21
4  bronze/thesportsdb/media/entity=team/team_id=1...   team    133604    fanart1   image/jpeg      212111  cached  https://r2.thesportsdb.com/images/media/team/f...  2026-09-21

  player_id former_team start_year end_year
0  34148681   Blackburn       2012     2014
1  34148681   Blackburn       2014     2019
2  34148681   Southport       2014     2015
3  34148681     Arsenal       2023     2024
4  34148681   Brentford       2019     2024

  player_id team_id          player_name nationality  birth_date wage date_signed signing_fee outfitter            agent      position                   height   weight wikidata_id transfermarkt_id espn_id
0  34192371  133597        Alex Cochrane     England  2000-04-21             None                           Midas Sports     Left-Back                   173 cm  152 lbs   Q75179071           392773  251627
1  34248066  133597        August Priske     Belgium  2004-03-23             None                                             Attacker                   187 cm    79 kg                         None    None
2  34296754  133597         Bradley Mayo     England  2004-09-15             None                                           Goalkeeper                     None                                  None  369486
3  34173570  133597  Bright Osayi-Samuel     Nigeria  1997-12-31             None                        Triple S Sports    Right-Back                   175 cm  159 lbs   Q19972631           358948  217071
4  34228159  133597       Carlos Vicente       Spain  1999-04-23             None       €600k                             Right Winger  1.79 m (5 ft 10+1⁄2 in)  159 lbs                       540536  172019

  team_id                 team_name team_short                                    alternate_names  formed_year                  league  country                      stadium  stadium_capacity                        stadium_location              website                                     description_en
0  133604                   Arsenal        ARS             Arsenal Football Club, AFC, Arsenal FC         1892  English Premier League  England             Emirates Stadium               NaN               Holloway, London, England      www.arsenal.com  Arsenal Football Club is a professional footba...
1  133601               Aston Villa        AVL                                     Aston Villa FC         1874  English Premier League  England                   Villa Park               NaN                       Aston, Birmingham       www.avfc.co.uk  Aston Villa Football Club is a professional fo...
2  134301               Bournemouth        BOU  AFC Bournemouth, Athletic Football Club Bourne...         1890  English Premier League  England             Vitality Stadium               NaN              AFCB, Bournemouth, England       www.afcb.co.uk  AFC Bournemouth is a professional football clu...
3  134355                 Brentford        BRE         Brentford Football Club, Brentford FC, BFC         1889  English Premier League  England  Brentford Community Stadium               NaN              Brentford, London, England  www.brentfordfc.com  Brentford Football Club is a professional foot...
4  133619  Brighton and Hove Albion        BRI  Brighton & Hove Albion Football Club, Brighton...         1901  English Premier League  England     American Express Stadium               NaN  Falmer, Brighton, East Sussex, England   www.seagulls.co.uk  Brighton & Hove Albion Football Club, commonly...

                                     club                clubLabel websiteURL club_qid  capacity inception
0  http://www.wikidata.org/entity/Q189012                Alex Song       None  Q189012       NaN       NaT
1  http://www.wikidata.org/entity/Q189184  Rafael Pereira da Silva       None  Q189184       NaN       NaT
2  http://www.wikidata.org/entity/Q189217              Davor Šuker       None  Q189217       NaN       NaT
3  http://www.wikidata.org/entity/Q189449           Yossi Benayoun       None  Q189449       NaN       NaT
4  http://www.wikidata.org/entity/Q189686         Patrick Kluivert       None  Q189686       NaN       NaT

   player_qid    playerLabel             clubs      positions           countries                       dob  height   age
0   Q10387687  Jimmy McNulty  ['Everton F.C.']   ['defender']  ['United Kingdom'] 1985-02-13 00:00:00+00:00  183.00  41.6
1      Q10869   Rachel Unitt  ['Everton F.C.']  ['full-back']  ['United Kingdom'] 1982-05-05 00:00:00+00:00    1.72  44.4
2  Q108690643   Lewis Dobbin  ['Everton F.C.']             []  ['United Kingdom'] 2003-01-03 00:00:00+00:00  175.00  23.7
3  Q115208158  Thomas Cannon  ['Everton F.C.']             []         ['Ireland'] 2002-12-28 00:00:00+00:00  180.00  23.7
4  Q116860945  Thierno Barry  ['Everton F.C.']             []          ['France'] 2002-10-21 00:00:00+00:00    1.95  23.9

                                      venue  capacity                             coord                opened                 venueLabel                    cityLabel    countryLabel  venue_qid       lon        lat
0     http://www.wikidata.org/entity/Q83457     75731  Point(-2.291388888 53.463055555)  1910-02-19T00:00:00Z               Old Trafford                      England  United Kingdom     Q83457 -2.291389  53.463056
1  http://www.wikidata.org/entity/Q55074091     62850  Point(-0.066388888 51.604444444)  2019-04-03T00:00:00Z  Tottenham Hotspur Stadium                    Tottenham  United Kingdom  Q55074091 -0.066389  51.604444
2     http://www.wikidata.org/entity/Q45671     61276  Point(-2.960833333 53.430833333)  1885-01-01T00:00:00Z                    Anfield                      Anfield  United Kingdom     Q45671 -2.960833  53.430833
3    http://www.wikidata.org/entity/Q163995     60338        Point(-0.108333333 51.555)  2006-07-22T00:00:00Z           Emirates Stadium  London Borough of Islington  United Kingdom    Q163995 -0.108333  51.555000
4     http://www.wikidata.org/entity/Q48159     52900  Point(-2.200277777 53.483055555)  2002-07-25T00:00:00Z             Etihad Stadium                   Manchester  United Kingdom     Q48159 -2.200278  53.483056

       id  minute       result      X      Y        xG           player h_a player_id situation season   shotType match_id               h_team            a_team h_goals a_goals                 date player_assisted lastAction side      league
0  585721       3  MissedShots  0.757  0.421  0.020014     Julian Weigl   h       372  OpenPlay   2024  RightFoot    27742  Borussia M.Gladbach  Bayer Leverkusen       2       3  2024-08-23 18:30:00            None       None    h  Bundesliga
1  585724      14    SavedShot  0.968  0.392  0.129965      Rocco Reitz   h      8826  OpenPlay   2024  RightFoot    27742  Borussia M.Gladbach  Bayer Leverkusen       2       3  2024-08-23 18:30:00            None     TakeOn    h  Bundesliga
2  585727      20    SavedShot  0.894  0.270  0.036669  Tim Kleindienst   h      6142  OpenPlay   2024  RightFoot    27742  Borussia M.Gladbach  Bayer Leverkusen       2       3  2024-08-23 18:30:00  Franck Honorat       Pass    h  Bundesliga
3  585729      29  BlockedShot  0.912  0.512  0.083535  Tim Kleindienst   h      6142  SetPiece   2024   LeftFoot    27742  Borussia M.Gladbach  Bayer Leverkusen       2       3  2024-08-23 18:30:00            None       None    h  Bundesliga
4  585730      29  BlockedShot  0.768  0.557  0.024129      Rocco Reitz   h      8826  SetPiece   2024  RightFoot    27742  Borussia M.Gladbach  Bayer Leverkusen       2       3  2024-08-23 18:30:00    Julian Weigl       Pass    h  Bundesliga

   fixture_id                       date          status               round  home_team_id          home_team  away_team_id    away_team  home_goals  away_goals  ht_home  ht_away      referee             venue ingest_date
0     1208021  2024-08-16T19:00:00+00:00  Match Finished  Regular Season - 1            33  Manchester United            36       Fulham           1           0        0        0     R. Jones      Old Trafford  2026-09-25
1     1208022  2024-08-17T11:30:00+00:00  Match Finished  Regular Season - 1            57            Ipswich            40    Liverpool           0           2        0        0  T. Robinson      Portman Road  2026-09-25
2     1208025  2024-08-17T14:00:00+00:00  Match Finished  Regular Season - 1            34          Newcastle            41  Southampton           1           0        1        0    C. Pawson   St. James' Park  2026-09-25
3     1208023  2024-08-17T14:00:00+00:00  Match Finished  Regular Season - 1            42            Arsenal            39       Wolves           2           0        1        0   J. Gillett  Emirates Stadium  2026-09-25
4     1208024  2024-08-17T14:00:00+00:00  Match Finished  Regular Season - 1            45            Everton            51     Brighton           0           3        0        1    S. Hooper     Goodison Park  2026-09-25

   fixture_id  team_id       team formation   role  player_id         player  number position grid
0     1208320       34  Newcastle     4-3-3  start      18911        N. Pope      22        G  1:1
1     1208320       34  Newcastle     4-3-3  start        169    K. Trippier       2        D  2:4
2     1208320       34  Newcastle     4-3-3  start       2806       F. Schär       5        D  2:3
3     1208320       34  Newcastle     4-3-3  start      18961        D. Burn      33        D  2:2
4     1208320       34  Newcastle     4-3-3  start     158694  T. Livramento      21        D  2:1

   fixture_id  minute  minute_extra       team  team_id     player  player_id        assist   type          detail comments
0     1208320      45           2.0  Newcastle       34    A. Isak       2864     J. Murphy   Goal     Normal Goal     None
1     1208320      59           NaN  Brentford       55  V. Janelt      25073  M. Damsgaard  subst  Substitution 1     None
2     1208320      66           NaN  Newcastle       34    A. Isak       2864     C. Wilson  subst  Substitution 1     None
3     1208320      66           NaN  Newcastle       34  J. Murphy      19163    J. Willock  subst  Substitution 2     None
4     1208320      66           NaN  Brentford       55  B. Mbeumo      20589          None   Goal         Penalty     None

   fixture_id            team  team_id  shots_on_goal  shots_off_goal  total_shots  blocked_shots  shots_insidebox  shots_outsidebox  fouls  corner_kicks  offsides  ball_possession  yellow_cards  red_cards  goalkeeper_saves  total_passes  passes_accurate  passes_pct expected_goals goals_prevented
0     1208320       Newcastle       34              4               9           21              8               15                 6     12             4       2.0             48.0           1.0        NaN                 2           398              303        76.0           1.43           -0.38
1     1208320       Brentford       55              3               3           12              6               10                 2     12             5       0.0             52.0           1.0        NaN                 2           424              327        77.0           1.63           -0.38
2     1208321     Southampton       41              2               3            8              3                7                 1     14             2       2.0             43.0           2.0        NaN                 2           388              302        78.0           0.51           -0.12
3     1208321  Crystal Palace       52              3               5            9              1                7                 2      9             2       4.0             57.0           1.0        NaN                 1           513              432        84.0           0.88           -0.12
4     1208322       Liverpool       40              3               5           17              9               11                 6      7            11       2.0             74.0           2.0        NaN                 0           601              525        87.0           1.39           -0.73

  Div match_date   Time      home_team   away_team  home_goals  away_goals result  HTHG  HTAG HTR  HS  AS  HST  AST  HC  AC  HY  AY  HR  AR  Referee division   season  total_goals                                    match_id  home_team_key away_team_key
0  D1 2020-09-18  19:30  Bayern Munich  Schalke 04           8           0      H     3     0   H  22   5   12    1   9   2   1   2   0   0      NaN       D1  2020-21            8  D1_2020-21_20200918_BayernMunich_Schalke04  Bayern Munich    Schalke 04
1  D1 2020-09-19  14:30  Ein Frankfurt   Bielefeld           1           1      D     0     0   D  18  14    6    4  14   3   2   2   0   0      NaN       D1  2020-21            2  D1_2020-21_20200919_EinFrankfurt_Bielefeld  Ein Frankfurt     Bielefeld
2  D1 2020-09-19  14:30        FC Koln  Hoffenheim           2           3      A     1     2   A  13  13    6    7   1   6   0   0   0   0      NaN       D1  2020-21            5       D1_2020-21_20200919_FCKoln_Hoffenheim        FC Koln    Hoffenheim
3  D1 2020-09-19  14:30      Stuttgart    Freiburg           2           3      A     0     2   A  22   7    7    6   7   2   2   2   0   0      NaN       D1  2020-21            5      D1_2020-21_20200919_Stuttgart_Freiburg      Stuttgart      Freiburg
4  D1 2020-09-19  14:30   Union Berlin    Augsburg           1           3      A     0     1   A  13   9    3    5   8   1   2   0   0   0      NaN       D1  2020-21            4    D1_2020-21_20200919_UnionBerlin_Augsburg   Union Berlin      Augsburg

  Div match_date   Time   home_team    away_team  home_goals  away_goals result  HTHG  HTAG HTR  HS  AS  HST  AST  HC  AC  HY  AY  HR  AR     Referee division   season  total_goals                                   match_id      home_team_key  away_team_key                   venue match_date_only  date  temperature_c  precipitation_mm  windspeed_kmh
0  E0 2024-08-16  20:00  Man United       Fulham           1           0      H     0     0   D  14  10    5    2   7   8   2   3   0   0     R Jones       E0  2024-25            1       E0_2024-25_20240816_ManUnited_Fulham  Manchester United         Fulham            Old Trafford      2024-08-16  None            NaN               NaN            NaN
1  E0 2024-08-17  12:30     Ipswich    Liverpool           0           2      A     0     0   D   7  18    2    5   2  10   3   1   0   0  T Robinson       E0  2024-25            2      E0_2024-25_20240817_Ipswich_Liverpool       Ipswich Town      Liverpool            Portman Road      2024-08-17  None            NaN               NaN            NaN
2  E0 2024-08-17  15:00     Arsenal       Wolves           2           0      H     1     0   H  18   9    6    3   8   2   2   2   0   0   J Gillett       E0  2024-25            2         E0_2024-25_20240817_Arsenal_Wolves            Arsenal  Wolverhampton        Emirates Stadium      2024-08-17  None            NaN               NaN            NaN
3  E0 2024-08-17  15:00     Everton     Brighton           0           3      A     0     1   A   9  10    1    5   1   5   1   1   1   0    S Hooper       E0  2024-25            3       E0_2024-25_20240817_Everton_Brighton            Everton       Brighton  Hill Dickinson Stadium      2024-08-17  None            NaN               NaN            NaN
4  E0 2024-08-17  15:00   Newcastle  Southampton           1           0      H     1     0   H   3  19    1    4   3  12   2   4   1   0    C Pawson       E0  2024-25            1  E0_2024-25_20240817_Newcastle_Southampton   Newcastle United    Southampton          St James’ Park      2024-08-17  None            NaN               NaN            NaN

   match_id competition  season_id  matchday           stage                  utc_date    status  home_team_id           home_team  away_team_id                 away_team  home_goals  away_goals     winner          referee
0    565776         BL1       2522         1  REGULAR_SEASON 2026-08-28 18:30:00+00:00  FINISHED             5   FC Bayern München            10             VfB Stuttgart         5.0         1.0  HOME_TEAM     Sören Storks
1    565777         BL1       2522         1  REGULAR_SEASON 2026-08-29 13:30:00+00:00  FINISHED           721          RB Leipzig            18  Borussia Mönchengladbach         3.0         0.0  HOME_TEAM   Sven Jablonski
2    565778         BL1       2522         1  REGULAR_SEASON 2026-08-29 13:30:00+00:00  FINISHED            15     1. FSV Mainz 05            29           SC Paderborn 07         0.0         0.0       DRAW   Tobias Stieler
3    565779         BL1       2522         1  REGULAR_SEASON 2026-08-29 13:30:00+00:00  FINISHED            28  1. FC Union Berlin            19       Eintracht Frankfurt         3.0         3.0       DRAW  Bastian Dankert
4    565780         BL1       2522         1  REGULAR_SEASON 2026-08-29 13:30:00+00:00  FINISHED           719    SV 07 Elversberg             3       Bayer 04 Leverkusen         3.0         2.0  HOME_TEAM  Robert Hartmann

      id  isResult                                                  h                                                  a                 goals                                 xG            datetime                                       forecast      league season
0  27742      True  {'id': '130', 'title': 'Borussia M.Gladbach', ...  {'id': '119', 'title': 'Bayer Leverkusen', 'sh...  {'h': '2', 'a': '3'}   {'h': '1.51665', 'a': '3.23588'} 2024-08-23 18:30:00   {'w': '0.074', 'd': '0.1487', 'l': '0.7773'}  Bundesliga   2024
1  27743      True  {'id': '136', 'title': 'RasenBallsport Leipzig...  {'id': '268', 'title': 'Bochum', 'short_title'...  {'h': '1', 'a': '0'}  {'h': '0.937134', 'a': '1.31541'} 2024-08-24 13:30:00  {'w': '0.2301', 'd': '0.2932', 'l': '0.4767'}  Bundesliga   2024
2  27744      True  {'id': '120', 'title': 'Hoffenheim', 'short_ti...  {'id': '287', 'title': 'Holstein Kiel', 'short...  {'h': '3', 'a': '2'}   {'h': '3.73706', 'a': '1.97238'} 2024-08-24 13:30:00  {'w': '0.7519', 'd': '0.1367', 'l': '0.1114'}  Bundesliga   2024
3  27745      True  {'id': '135', 'title': 'Freiburg', 'short_titl...  {'id': '133', 'title': 'VfB Stuttgart', 'short...  {'h': '3', 'a': '1'}   {'h': '3.0149', 'a': '0.374185'} 2024-08-24 13:30:00   {'w': '0.953', 'd': '0.0388', 'l': '0.0082'}  Bundesliga   2024
4  27746      True  {'id': '121', 'title': 'Augsburg', 'short_titl...  {'id': '123', 'title': 'Werder Bremen', 'short...  {'h': '2', 'a': '2'}   {'h': '1.31571', 'a': '1.54312'} 2024-08-24 13:30:00  {'w': '0.3003', 'd': '0.2921', 'l': '0.4076'}  Bundesliga   2024

                                              s3_key entity entity_id   role  size_bytes                                             sha256                                         source_url ingest_date
0  bronze/api_football/media/entity=team/team_id=...   team        33   logo       90381  6dff7e1a3d7d7a3748edf8ca55fefa00aa169a47f1933b...  https://media.api-sports.io/football/teams/33.png  2026-09-25
1  bronze/api_football/media/entity=venue/venue_i...  venue       556  photo       66527  53c2d32b32a3bffbe38d6d52bca7a1aac52748066fc19a...  https://media.api-sports.io/football/venues/55...  2026-09-25
2  bronze/api_football/media/entity=team/team_id=...   team        34   logo       89769  2cdfd5d4d0e6d97f3b452a10e648a1bbdc6d3ca34c8609...  https://media.api-sports.io/football/teams/34.png  2026-09-25
3  bronze/api_football/media/entity=venue/venue_i...  venue       562  photo      100415  93000f0af067e7bb8371ca3bcf9bd09833a68f319627e7...  https://media.api-sports.io/football/venues/56...  2026-09-25
4  bronze/api_football/media/entity=team/team_id=...   team        35   logo       15197  e668d998ce23dc34648ce4c7f19d289d0fbb567383bf06...  https://media.api-sports.io/football/teams/35.png  2026-09-25

                                               title                                                url                                              image  source              published_at ingest_date
0  Mexico vs. Colombia—International Friendly: Pr...  https://www.si.com/soccer/mexico-vs-colombia-i...  https://images2.minutemediacdn.com/image/uploa...  90mins  2026-09-26T03:12:08.557Z  2026-09-26
1  England vs. Spain—Nations League: Preview, Pre...  https://www.si.com/soccer/england-vs-spain-nat...  https://images2.minutemediacdn.com/image/uploa...  90mins  2026-09-26T03:12:08.558Z  2026-09-26
2  Chelsea or Liverpool: Who Needs Lamine Camara ...  https://www.si.com/soccer/chelsea-liverpool-wh...  https://images2.minutemediacdn.com/image/uploa...  90mins  2026-09-26T03:12:08.559Z  2026-09-26
3  USMNT vs. Peru—International Friendly: Preview...  https://www.si.com/soccer/usmnt-vs-peru-intern...  https://images2.minutemediacdn.com/image/uploa...  90mins  2026-09-26T03:12:08.559Z  2026-09-26
4  MLS Predictions: Playoff Races Heat Up Ahead o...  https://www.si.com/soccer/mls-predictions-play...  https://images2.minutemediacdn.com/image/uploa...  90mins  2026-09-26T03:12:08.559Z  2026-09-26

                                     match_id bookmaker  odds_home  odds_draw  odds_away  implied_margin
0  D1_2020-21_20200918_BayernMunich_Schalke04      B365       1.10       11.0      21.00          0.0476
1  D1_2020-21_20200919_EinFrankfurt_Bielefeld      B365       1.61        4.2       5.25          0.0497
2       D1_2020-21_20200919_FCKoln_Hoffenheim      B365       2.60        3.5       2.60          0.0549
3      D1_2020-21_20200919_Stuttgart_Freiburg      B365       2.25        3.5       3.10          0.0527
4    D1_2020-21_20200919_UnionBerlin_Augsburg      B365       2.30        3.3       3.20          0.0503

   player_id      player             type           reason  team_id               team  fixture_id               fixture_date ingest_date
0     153434     W. Fish  Missing Fixture     Ankle Injury       33  Manchester United     1208021  2024-08-16T19:00:00+00:00  2026-09-25
1     288006  R. Hojlund  Missing Fixture    Muscle Injury       33  Manchester United     1208021  2024-08-16T19:00:00+00:00  2026-09-25
2      37145  T. Malacia  Missing Fixture      Knee Injury       33  Manchester United     1208021  2024-08-16T19:00:00+00:00  2026-09-25
3        891     L. Shaw  Missing Fixture  Health problems       33  Manchester United     1208021  2024-08-16T19:00:00+00:00  2026-09-25
4     342970     L. Yoro  Missing Fixture     Ankle Injury       33  Manchester United     1208021  2024-08-16T19:00:00+00:00  2026-09-25

   player_id          name       firstname            lastname  age  nationality height weight                                          photo_url  team_id             team    position  appearances  minutes  goals  assists  yellow_cards  red_cards  shots_total  shots_on  passes_total  passes_key  dribbles_att  dribbles_ok    rating ingest_date
0          5     M. Akanji  Manuel Obafemi              Akanji   30  Switzerland    188     91  https://media.api-sports.io/football/players/5...       50  Manchester City    Defender         28.0   2020.0    NaN      0.0           3.0        0.0         10.0       2.0        1721.0         9.0           2.0          2.0  7.000000  2026-09-22
1         14     M. Dahoud         Mahmoud              Dahoud   29      Germany    178     68  https://media.api-sports.io/football/players/1...       51         Brighton  Midfielder          0.0      0.0    0.0      NaN           0.0        0.0          NaN       NaN           NaN         NaN           NaN          NaN      None  2026-09-22
2         18     J. Sancho     Jadon Malik              Sancho   25      England    180     76  https://media.api-sports.io/football/players/1...       49          Chelsea    Attacker         31.0   1764.0    3.0      4.0           2.0        0.0         12.0       8.0         768.0        38.0          86.0         45.0  6.964516  2026-09-22
3         23  Sergio Gómez          Sergio        Gómez Martín   25        Spain    173     71  https://media.api-sports.io/football/players/2...       50  Manchester City    Attacker          0.0      0.0    0.0      NaN           0.0        0.0          NaN       NaN           NaN         NaN           NaN          NaN      None  2026-09-22
4         44         Rodri         Rodrigo  Hernández Cascante   29        Spain    190     82  https://media.api-sports.io/football/players/4...       50  Manchester City  Midfielder          5.0     80.0    NaN      0.0           0.0        0.0          NaN       NaN          68.0         1.0           NaN          NaN  6.833333  2026-09-22

   player_id         player  nationality  age               team  goals  assists  appearances  minutes ingest_date
0       1165  Matheus Cunha       Brazil   26  Manchester United     30       12           66     5203  2026-09-25
1        306  Mohamed Salah        Egypt   33          Liverpool     29       18           38     3377  2026-09-25
2       2864        A. Isak       Sweden   26          Newcastle     23        6           34     2769  2026-09-25
3       1100     E. Haaland       Norway   25    Manchester City     22        3           32     2741  2026-09-25
4      18931        C. Wood  New Zealand   34  Nottingham Forest     20        3           36     2978  2026-09-25

              team      player_name injury_type ingest_date
0  AFC Bournemouth  Justin Kluivert        Knee  2026-09-21
1  AFC Bournemouth       Lewis Cook       Thigh  2026-09-21
2  AFC Bournemouth      Tyler Adams       Other  2026-09-21
3  AFC Bournemouth      Julio Soler       Other  2026-09-21
4          Arsenal     Mikel Merino  Ankle/Foot  2026-09-21

     id        player_name  games  time  goals         xG  assists        xA  shots  key_passes  yellow_cards  red_cards position           team_title  npg       npxG    xGChain  xGBuildup  xg_per90  goals_minus_xg  xA_per90  xGChain_per90      league season ingest_date
0   647         Harry Kane     31  2400     26  24.838503        9  5.889719    114          36             5          0      F S        Bayern Munich   17  18.018513  30.192511   8.705299  0.931444        1.161497  0.220864       1.132219  Bundesliga   2024  2026-09-25
1  1236      Patrik Schick     31  1675     21  13.808414        0  0.893107     68          11             4          0    F M S     Bayer Leverkusen   20  13.050637  13.012596   2.174655  0.741945        7.191586  0.047988       0.699184  Bundesliga   2024  2026-09-25
2  3738    Serhou Guirassy     30  2608     21  24.675027        2  3.927161     89          25             4          0      F S    Borussia Dortmund   18  21.643921  28.848952   5.983426  0.851516       -3.675027  0.135523       0.995554  Bundesliga   2024  2026-09-25
3  7108  Jonathan Burkardt     29  2144     18  15.531241        2  3.226014     72          20             0          0      F S             Mainz 05   16  14.015688  17.678049   2.238999  0.651964        2.468759  0.135420       0.742082  Bundesliga   2024  2026-09-25
4  6142    Tim Kleindienst     31  2756     16  15.641376        7  6.164369     75          28             3          1        F  Borussia M.Gladbach   15  14.125823  22.164080   5.898255  0.510785        0.358624  0.201304       0.723791  Bundesliga   2024  2026-09-25

   rank             team  team_id  points  played  win  draw  lose  goals_for  goals_against  goal_diff   form ingest_date
0     1        Liverpool       40      84      38   25     9     4         86             41         45  DLDLW  2026-09-25
1     2          Arsenal       42      74      38   20    14     4         69             34         35  WWDLD  2026-09-25
2     3  Manchester City       50      71      38   21     8     9         72             44         28  WWDWW  2026-09-25
3     4          Chelsea       49      69      38   20     9     9         64             43         21  WWLWW  2026-09-25
4     5        Newcastle       34      66      38   20     6    12         68             47         21  LLWDW  2026-09-25

  competition ingest_date  rank  team_id                 team  played  won  draw  lost  points  goals_for  goals_against  goal_diff  form
0         BL1  2026-09-27     1        4    Borussia Dortmund       4    4     0     0      12          9              2          7  None
1         BL1  2026-09-27     2        5    FC Bayern München       4    3     1     0      10         14              2         12  None
2         BL1  2026-09-27     3       17          SC Freiburg       4    3     1     0      10         12              3          9  None
3         BL1  2026-09-27     4       16          FC Augsburg       4    2     1     1       7         11              6          5  None
4         BL1  2026-09-27     5        3  Bayer 04 Leverkusen       4    2     1     1       7         10              5          5  None

  team_id      team_name                date h_a       xG       xGA     npxG     npxGA result       ppda  scored  missed  wins  draws  loses  pts      league season
0     117  Bayern Munich 2024-08-25 13:30:00   a  2.17538  2.081250  2.17538  1.323480      w   7.125000       3       2     1      0      0    3  Bundesliga   2024
1     117  Bayern Munich 2024-09-01 15:30:00   h  1.62797  0.970892  0.87019  0.213115      w   9.350000       2       0     1      0      0    3  Bundesliga   2024
2     117  Bayern Munich 2024-09-14 16:30:00   a  4.13442  0.299776  3.37664  0.299776      w  10.736842       6       1     1      0      0    3  Bundesliga   2024
3     117  Bayern Munich 2024-09-21 13:30:00   a  3.34451  0.000000  3.34451  0.000000      w   7.312500       5       0     1      0      0    3  Bundesliga   2024
4     117  Bayern Munich 2024-09-28 16:30:00   h  1.19457  0.087016  1.19457  0.087016      d   7.040000       1       1     0      1      0    1  Bundesliga   2024

          feed                   query lang                                              title                                            summary                                               link                      published           source                                               guid              published_ts                                               text ingest_date
0  google-news  Bóng đá Ngoại hạng Anh   vi  Video bóng đá Fulham - MU: Cay đắng phản lưới,...  Video bóng đá Fulham - MU: Cay đắng phản lưới,...  https://news.google.com/rss/articles/CBMixAFBV...  Sun, 20 Sep 2026 17:41:58 GMT      Tin tức 24h  CBMixAFBVV95cUxPc0RrWTlXWUlqV0ZxTU9tMmkwTGhNWH... 2026-09-20 17:41:58+00:00  Video bóng đá Fulham - MU: Cay đắng phản lưới,...  2026-09-21
1  google-news  Bóng đá Ngoại hạng Anh   vi  Bảng xếp hạng Ngoại hạng Anh 2026/27 vòng 5: T...  Bảng xếp hạng Ngoại hạng Anh 2026/27 vòng 5: T...  https://news.google.com/rss/articles/CBMirwFBV...  Sun, 20 Sep 2026 18:10:43 GMT  Tạp chí Bóng đá  CBMirwFBVV95cUxPdzJHT0ZJMFZYY0VVVU1jOEpQVFZGTl... 2026-09-20 18:10:43+00:00  Bảng xếp hạng Ngoại hạng Anh 2026/27 vòng 5: T...  2026-09-21
2  google-news  Bóng đá Ngoại hạng Anh   vi  Nhận định bóng đá Man City vs Sunderland, 20h0...  Nhận định bóng đá Man City vs Sunderland, 20h0...  https://news.google.com/rss/articles/CBMi2gFBV...  Sun, 20 Sep 2026 11:34:31 GMT  Tạp chí Bóng đá  CBMi2gFBVV95cUxOMHgyekF0VnhBb2pQdExtTXIwN2M2R3... 2026-09-20 11:34:31+00:00  Nhận định bóng đá Man City vs Sunderland, 20h0...  2026-09-21
3  google-news  Bóng đá Ngoại hạng Anh   vi      Kết quả bóng đá hôm nay 21/9 - Báo VietNamNet  Kết quả bóng đá hôm nay 21/9&nbsp;&nbsp;Báo Vi...  https://news.google.com/rss/articles/CBMicEFVX...  Sun, 20 Sep 2026 22:07:00 GMT   Báo VietNamNet  CBMicEFVX3lxTFBEWXU0empaUlBVdmhjdmtEckx6b0Fvc3... 2026-09-20 22:07:00+00:00  Kết quả bóng đá hôm nay 21/9 - Báo VietNamNet....  2026-09-21
4  google-news  Bóng đá Ngoại hạng Anh   vi  Lương của các câu lạc bộ Ngoại hạng Anh được t...  Lương của các câu lạc bộ Ngoại hạng Anh được t...  https://news.google.com/rss/articles/CBMiowFBV...  Sun, 20 Sep 2026 12:32:13 GMT        Bongda24h  CBMiowFBVV95cUxPR2pNeGJ0czdqV0JTYzduNmVLNkxFMz... 2026-09-20 12:32:13+00:00  Lương của các câu lạc bộ Ngoại hạng Anh được t...  2026-09-21

                              title entity_type lang  page_id                                            extract  word_count fetched_date
0  2005 UEFA Champions League final     history   en  4861876  The 2005 UEFA Champions League final was the f...        4409   2026-09-27
1                    Premier League     history   en    11250  The Premier League is a professional associati...       10055   2026-09-27

  entity_type                 article              label lang       date  views  year  month  week_of_year  day_of_week  is_weekend football_season  views_7d_avg  views_28d_avg  views_28d_std   zscore  spike_ratio_7d  is_spike
0        team   Newcastle_United_F.C.   Newcastle United   de 2025-01-11      1  2025      1             2            5           1       2024/2025      0.142857       0.035714       0.188982  5.10252             NaN         1
1        team  Tottenham_Hotspur_F.C.  Tottenham Hotspur   de 2023-05-25      1  2023      5            21            3           0       2022/2023      0.142857       0.035714       0.188982  5.10252             NaN         1
2        team    Manchester_City_F.C.    Manchester City   de 2024-12-27      1  2024     12            52            4           0       2024/2025      0.142857       0.035714       0.188982  5.10252             NaN         1
3        team  Tottenham_Hotspur_F.C.  Tottenham Hotspur   de 2024-10-10      1  2024     10            41            3           0       2024/2025      0.142857       0.035714       0.188982  5.10252             NaN         1
4        team     Crystal_Palace_F.C.     Crystal Palace   fr 2024-12-14      1  2024     12            50            5           1       2024/2025      0.142857       0.035714       0.188982  5.10252             NaN         1

  entity_type         article           label       date  views  year  month  week_of_year  day_of_week  is_weekend football_season  views_7d_avg  views_28d_avg  views_28d_std    zscore  spike_ratio_7d  is_spike
0      player  Alexander_Isak  Alexander Isak 2023-01-01   1628  2023      1            52            6           1       2022/2023        1628.0         1628.0            NaN       NaN             NaN         0
1      player  Alexander_Isak  Alexander Isak 2023-01-02   2048  2023      1             1            0           0       2022/2023        1838.0         1838.0            NaN       NaN             NaN         0
2      player  Alexander_Isak  Alexander Isak 2023-01-03   3986  2023      1             1            1           0       2022/2023        2554.0         2554.0            NaN       NaN             NaN         0
3      player  Alexander_Isak  Alexander Isak 2023-01-04   2372  2023      1             1            2           0       2022/2023        2508.5         2508.5            NaN       NaN        0.928739         0
4      player  Alexander_Isak  Alexander Isak 2023-01-05   1553  2023      1             1            3           0       2022/2023        2317.4         2317.4     989.869082 -0.772223        0.619095         0

  entity_type         article           label lang       date  views  year  month  week_of_year  day_of_week  is_weekend football_season  views_7d_avg  views_28d_avg  views_28d_std    zscore  spike_ratio_7d  is_spike
0      player  Alexander_Isak  Alexander Isak   de 2023-01-01     65  2023      1            52            6           1       2022/2023         65.00          65.00            NaN       NaN             NaN         0
1      player  Alexander_Isak  Alexander Isak   de 2023-01-02     56  2023      1             1            0           0       2022/2023         60.50          60.50            NaN       NaN             NaN         0
2      player  Alexander_Isak  Alexander Isak   de 2023-01-03    152  2023      1             1            1           0       2022/2023         91.00          91.00            NaN       NaN             NaN         0
3      player  Alexander_Isak  Alexander Isak   de 2023-01-04     86  2023      1             1            2           0       2022/2023         89.75          89.75            NaN       NaN        0.945055         0
4      player  Alexander_Isak  Alexander Isak   de 2023-01-05     51  2023      1             1            3           0       2022/2023         82.00          82.00      41.358191 -0.749549        0.568245         0

                   comment_id     video_id             author                                               text  like_count          published_at              published_ts ingest_date
0  UgwhJaZNIMg6dBgnLt54AaABAg  GAvCftCXL0E   @brunosantos6595  Congratulations Liverpool, great victory! Gree...           1  2026-09-21T08:30:46Z 2026-09-21 08:30:46+00:00  2026-09-21
1  Ugy5-dq4aFWDKyKyeeB4AaABAg  GAvCftCXL0E           @ooolega                   Witz is threre! as always my man           0  2026-09-21T08:23:53Z 2026-09-21 08:23:53+00:00  2026-09-21
2  UgyAL_rAcCrVBma-ZFB4AaABAg  GAvCftCXL0E  @UnbelievableJeff  i love Liverpool but i'd rather watch Brighton...           0  2026-09-21T08:19:09Z 2026-09-21 08:19:09+00:00  2026-09-21
3  UgwyB3hcYEBK-YaT2Ul4AaABAg  GAvCftCXL0E       @litsitsomf2  Allison becker has been sooooo good this seaso...           0  2026-09-21T08:18:58Z 2026-09-21 08:18:58+00:00  2026-09-21
4  UgwfIwxrpYKOeVSbt7B4AaABAg  GAvCftCXL0E      @johnyboy2934  i mean 2026 is full of surprises , who thought...           0  2026-09-21T08:16:59Z 2026-09-21 08:16:59+00:00  2026-09-21

      video_id                     query          published_at                channel_id                                              title                                        description     channel_title              published_ts ingest_date
0  GAvCftCXL0E  Ngoại hạng Anh highlight  2026-09-20T21:00:28Z  UC9LQwHZoucFT94I2h6JOcjw  Highlights: Bournemouth 0-1 Liverpool | Isak G...  Watch highlights from Liverpool's 1-0 victory ...      Liverpool FC 2026-09-20 21:00:28+00:00  2026-09-21
1  EFPDyDeB2HI  Ngoại hạng Anh highlight  2026-09-20T12:59:55Z  UCbkllEQivzBHCkaQX-w4N3Q  Highlights: Thành Phố Đồng Nai - Công An Hà Nộ...  Xem trọn Ngoại Hạng Anh, Truyền Hình, Giải Trí...  BÓNG ĐÁ VIỆT NAM 2026-09-20 12:59:55+00:00  2026-09-21
2  gIPTUHoGnDM  Ngoại hạng Anh highlight  2026-09-20T14:56:34Z  UCrVFnGI-iQLDHpwxUe1Q8Jg  Manchester City vs Sunderland Highlights 5-3 C...  Manchester City vs Sunderland Highlights | CHE...        Footballia 2026-09-20 14:56:34+00:00  2026-09-21
3  ctznPsjTgi8  Ngoại hạng Anh highlight  2026-09-20T12:22:41Z  UCbkllEQivzBHCkaQX-w4N3Q  Highlights: Hoàng Anh Gia Lai - Hưng Yên | Hiệ...  Xem trọn Ngoại Hạng Anh, Truyền Hình, Giải Trí...  BÓNG ĐÁ VIỆT NAM 2026-09-20 12:22:41+00:00  2026-09-21
4  jbXc4VgoglA  Ngoại hạng Anh highlight  2026-09-13T21:00:37Z  UCG5qGWdu8nIRZqJ_GgDwQ-w  EVERY Weekend Goal | Matchweek 4 | 2026/27 Pre...  Love this video? We've got even more for you t...    Premier League 2026-09-13 21:00:37+00:00  2026-09-21